/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AuthenticatedAquisicoesRouteImport } from './routes/_authenticated/aquisicoes'
import { Route as AuthenticatedDashboardRouteImport } from './routes/_authenticated/dashboard'
import { Route as AuthenticatedTrocasRouteImport } from './routes/_authenticated/trocas'
import { Route as AuthenticatedVendasRouteImport } from './routes/_authenticated/vendas'
import { Route as AuthenticatedItensIndexRouteImport } from './routes/_authenticated/itens.index'
import { Route as AuthenticatedItensIdRouteImport } from './routes/_authenticated/itens.$id'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedAquisicoesRoute = AuthenticatedAquisicoesRouteImport.update({
  id: '/aquisicoes',
  path: '/aquisicoes',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedDashboardRoute = AuthenticatedDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedTrocasRoute = AuthenticatedTrocasRouteImport.update({
  id: '/trocas',
  path: '/trocas',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedVendasRoute = AuthenticatedVendasRouteImport.update({
  id: '/vendas',
  path: '/vendas',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedItensIndexRoute = AuthenticatedItensIndexRouteImport.update({
  id: '/itens/',
  path: '/itens/',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedItensIdRoute = AuthenticatedItensIdRouteImport.update({
  id: '/itens/$id',
  path: '/itens/$id',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/aquisicoes': typeof AuthenticatedAquisicoesRoute
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/trocas': typeof AuthenticatedTrocasRoute
  '/vendas': typeof AuthenticatedVendasRoute
  '/itens/$id': typeof AuthenticatedItensIdRoute
  '/itens/': typeof AuthenticatedItensIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/aquisicoes': typeof AuthenticatedAquisicoesRoute
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/trocas': typeof AuthenticatedTrocasRoute
  '/vendas': typeof AuthenticatedVendasRoute
  '/itens/$id': typeof AuthenticatedItensIdRoute
  '/itens': typeof AuthenticatedItensIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/auth': typeof AuthRoute
  '/_authenticated/aquisicoes': typeof AuthenticatedAquisicoesRoute
  '/_authenticated/dashboard': typeof AuthenticatedDashboardRoute
  '/_authenticated/trocas': typeof AuthenticatedTrocasRoute
  '/_authenticated/vendas': typeof AuthenticatedVendasRoute
  '/_authenticated/itens/$id': typeof AuthenticatedItensIdRoute
  '/_authenticated/itens/': typeof AuthenticatedItensIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/aquisicoes'
    | '/dashboard'
    | '/trocas'
    | '/vendas'
    | '/itens/$id'
    | '/itens/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/aquisicoes'
    | '/dashboard'
    | '/trocas'
    | '/vendas'
    | '/itens/$id'
    | '/itens'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/auth'
    | '/_authenticated/aquisicoes'
    | '/_authenticated/dashboard'
    | '/_authenticated/trocas'
    | '/_authenticated/vendas'
    | '/_authenticated/itens/$id'
    | '/_authenticated/itens/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  AuthRoute: typeof AuthRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/aquisicoes': {
      id: '/_authenticated/aquisicoes'
      path: '/aquisicoes'
      fullPath: '/aquisicoes'
      preLoaderRoute: typeof AuthenticatedAquisicoesRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/dashboard': {
      id: '/_authenticated/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof AuthenticatedDashboardRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/trocas': {
      id: '/_authenticated/trocas'
      path: '/trocas'
      fullPath: '/trocas'
      preLoaderRoute: typeof AuthenticatedTrocasRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/vendas': {
      id: '/_authenticated/vendas'
      path: '/vendas'
      fullPath: '/vendas'
      preLoaderRoute: typeof AuthenticatedVendasRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/itens/': {
      id: '/_authenticated/itens/'
      path: '/itens'
      fullPath: '/itens/'
      preLoaderRoute: typeof AuthenticatedItensIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/itens/$id': {
      id: '/_authenticated/itens/$id'
      path: '/itens/$id'
      fullPath: '/itens/$id'
      preLoaderRoute: typeof AuthenticatedItensIdRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
  }
}

interface AuthenticatedRouteRouteChildren {
  AuthenticatedAquisicoesRoute: typeof AuthenticatedAquisicoesRoute
  AuthenticatedDashboardRoute: typeof AuthenticatedDashboardRoute
  AuthenticatedTrocasRoute: typeof AuthenticatedTrocasRoute
  AuthenticatedVendasRoute: typeof AuthenticatedVendasRoute
  AuthenticatedItensIdRoute: typeof AuthenticatedItensIdRoute
  AuthenticatedItensIndexRoute: typeof AuthenticatedItensIndexRoute
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedAquisicoesRoute: AuthenticatedAquisicoesRoute,
  AuthenticatedDashboardRoute: AuthenticatedDashboardRoute,
  AuthenticatedTrocasRoute: AuthenticatedTrocasRoute,
  AuthenticatedVendasRoute: AuthenticatedVendasRoute,
  AuthenticatedItensIdRoute: AuthenticatedItensIdRoute,
  AuthenticatedItensIndexRoute: AuthenticatedItensIndexRoute,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  AuthRoute: AuthRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
